// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;
using System.Drawing;

#if __UNIFIED__
using Foundation;
using UIKit;
using CoreGraphics;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.CoreGraphics;
#endif
using Xamarin.Themes;

namespace ThemeSample {
	public partial class OtherView : UIView {
		public OtherView (IntPtr handle) : base (handle)
		{
		}

		public override void MovedToWindow ()
		{
			base.MovedToWindow ();

			InitSubviews ();
			ApplyStyles ();
		}

		void InitSubviews ()
		{
			var label = new UILabel () {
				Text = "Other tab",
				BackgroundColor = UIColor.Clear,
				TextColor = UIColor.White,
				ShadowColor = UIColor.DarkGray,
				ShadowOffset = new SizeF(0, 1),
				Font = UIFont.SystemFontOfSize(24)
			};

			label.Layer.AnchorPoint = new PointF (0.5f, 0.5f);
			label.SizeToFit();

			label.Center = new PointF ((float)Frame.GetMidX (), (float)Frame.GetMidY ());

			Add (label);
		}

		void ApplyStyles ()
		{
			GunmetalTheme.Apply (this);
		}
	}
}
