// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

#if __UNIFIED__
using Foundation;
using UIKit;
#else
using MonoTouch.Foundation;
using MonoTouch.UIKit;
#endif

namespace ThemeSample {
	public partial class MasterCell : UITableViewCell {
		public UILabel TitleLabel { get { return titleLabel; } }
		public UILabel DescriptionLabel { get { return descriptionLabel; } }
		public UIImageView DisclosureImageView { get { return disclosureImageView; } }
		public UIImageView AvatarImageView { get { return avatarImageView; } }
		public UIImageView BackgroundImageView { get { return backgroundImageView; } }

		public MasterCell (IntPtr handle) : base (handle)
		{

		}
	}
}
